apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
data:
  nginx.conf: |
    events {}
    http {
      upstream apache_backend {
        server {{ .Values.apache1.name }}:80;
        server {{ .Values.apache2.name }}:80;
      }
      server {
        listen 80;
        location / {
          proxy_pass http://apache_backend;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: nginx-proxy
  template: 
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
spec:
  type: {{ .Values.nginx.serviceType }}
  ports:
  - port: 80
    targetPort: 80
    nodePort: {{ .Values.nginx.nodePort }}
  selector:
    app: nginx-proxy